### ISSUE TITLE
Can't compile, glm/vec2 missing

### ISSUE THREAD

**Issue by soaresden** [ITotalJustice/untitled#3]
Hi, 
I would like to try myself the issues I opened, so I would like to compile it.
Unfotunately, can't because of files missing 

![image](https://user-images.githubusercontent.com/54243866/115534884-867d0100-a298-11eb-9c80-47abaa8c656c.png)

**Comment by ITotalJustice** [comment]
hi, sorry i did not see this issue (or the other that you opened!)

did you manage to solve this issue?

**Comment by soaresden** [comment]
no at all, please check

**Comment by ITotalJustice** [comment]
hi, once again, very sorry its taken this long!

the missing glm header was because you needed to install glm using dkp-pacman like so `pacman -S switch-glm`

if building still isn't working for you, feel free to comment on this issue again and i'll repon it
